// <auto-generated />
using HotelListing.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelListing.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220116042646_SeedDumpData")]
    partial class SeedDumpData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HotelListing.DataAccess.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vietnam",
                            ShortName = "VN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "United States",
                            ShortName = "US"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Australia",
                            ShortName = "AUS"
                        });
                });

            modelBuilder.Entity("HotelListing.DataAccess.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Vung Tau",
                            CountryId = 1,
                            Name = "Pullman",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ho Chi Minh",
                            CountryId = 1,
                            Name = "Sheraton",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 3,
                            Address = "Sydney",
                            CountryId = 3,
                            Name = "Park Hyatt Sydney",
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 4,
                            Address = "Las Vegas",
                            CountryId = 2,
                            Name = "Luxor Hotel & Casino",
                            Rating = 4.2000000000000002
                        });
                });

            modelBuilder.Entity("HotelListing.DataAccess.Hotel", b =>
                {
                    b.HasOne("HotelListing.DataAccess.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
